#!/bin/bash
#SBATCH --job-name=sBdCoupling_fino
#SBATCH --output foam1preprocess.log
#SBATCH --ntasks=32
#SBATCH --time=1:00:00
#SBATCH --account=car

source $HOME/.bash_profile
cores=$SLURM_NTASKS

echo "Working directory is" $SLURM_SUBMIT_DIR
echo "Job name is" $SLURM_JOB_NAME
echo "Submit time is" $(squeue -u $USER -o '%30j %20V' | grep -e $SLURM_JOB_NAME | awk '{print $2}')
echo "Starting OpenFOAM job at: " $(date)
echo "using" $cores "core(s)"

# ******************************************** USER INPUT ******************************************** #
OpenFOAM-6-gcc-dev        # OpenFOAM/SOWFA version. OpenFOAM-6-{gcc,intel}-{central,dev}
startTime=0               # Start time

# trying for now nosources, but ideally the many-level forces need to be implemented
#cp constant/ABLProperties.upperDamping.wrf       constant/ABLProperties
cp constant/ABLProperties.upperDamping.noSources  constant/ABLProperties

# Check the number of stacked refinements below and make sure the topoSetDict.level.* exists
# Check if the damping layers are appropriate
# **************************************************************************************************** #

# ***************************** COPY APPROPRIATE FILES AND SET VARIABLES ***************************** #
cp system/controlDict.singleTimeStep                   system/controlDict
cp system/fvSchemes.flow.linearupwind                  system/fvSchemes
cp setUp.wrf.1block                                    setUp
cp system/blockMeshDict.unifRes                        system/blockMeshDict
rm -f problemFaces
rm -rf constant/polyMesh
rm -rf constant/boundaryData
rm -rf $startTime
# **************************************************************************************************** #

refineMeshLocal()
{
    # Perform the levels refinement backwards
    for  ((i=$1; i>0; i--)); do
        topoSet -dict system/topoSetDict.level.$i -noFunctionObjects > log.1.topoSet.level.$i 2>&1
        refineHexMesh -overwrite -noFunctionObjects level.$i > log.1.refineHexMesh.level.$i 2>&1
        checkMesh -noFunctionObjects > log.1.checkMesh.level.$i 2>&1
    done
}

# Copy the "clean" .original initial fields to a working copy
cp -rf $startTime.original $startTime

# Build the mesh
blockMesh -noFunctionObjects > log.1.blockMesh 2>&1

# Create the stacked grid by means of refinements
refineMeshLocal 3

echo "Ending OpenFOAM job at: " $(date)

# **************************************************************************************************** #
