#!/bin/bash
#SBATCH --job-name=sOffshore
#SBATCH --output foam1preprocess.log
#SBATCH --ntasks=36
#SBATCH --time=2:00:00
#SBATCH --account=mmc

source $HOME/.bash_profile
cores=$SLURM_NTASKS

echo "Working directory is" $SLURM_SUBMIT_DIR
echo "Job name is" $SLURM_JOB_NAME
echo "Submit time is" $(squeue -u $USER -o '%30j %20V' | grep -e $SLURM_JOB_NAME | awk '{print $2}')
echo "Starting OpenFOAM job at: " $(date)
echo "using" $cores "core(s)"

# ******************************************** USER INPUT ******************************************** #
OpenFOAM-6-gcc-dev              # OpenFOAM/SOWFA version. OpenFOAM-6-{gcc,intel}-{central,dev}
startTime=113200                # Start time
stabState=wrf                   # neutral, stable, unstable, wrf
solver=superDeliciousVanilla

cp constant/ABLProperties.upperdamping.lessRAM          constant/ABLProperties
cp system/sampling/vmasts_1kmGrid.bak                   system/sampling/vmasts_1kmGrid
cp system/sampling/vmasts_small3x3Grid.bak              system/sampling/vmasts_small3x3Grid
cp system/sampling/slicesFINO1_correlation.bak          system/sampling/slicesFINO1_correlation
# **************************************************************************************************** #

# **************************************** PERFORM SOME CHECKS *************************************** #
if [ ! -f system/controlDict.$solver.startAt$startTime ]; then echo "Job killed (1)"; scancel $SLURM_JOBID; fi
if [ ! -f setUp.$stabState ];                             then echo "Job killed (2)"; scancel $SLURM_JOBID; fi
# **************************************************************************************************** #

# ************************************ COPYING APPROPRIATE FILES ************************************* #
cp system/controlDict.$solver.startAt$startTime        system/controlDict
cp setUp.$stabState                                    setUp
cp $startTime.original/qwall.$stabState                $startTime.original/qwall
# **************************************************************************************************** #

# Copy the "clean" .original initial fields to a working copy
rm -rf $startTime
cp -rf $startTime.original $startTime
rm     $startTime/qwall.*

# Build the mesh and check it
blockMesh -noFunctionObjects > log.1.blockMesh 2>&1
checkMesh -noFunctionObjects > log.1.checkMesh.background 2>&1

echo "Ending OpenFOAM job at: " $(date)

# **************************************************************************************************** #
